name: Build and Push Docker Image to GCR

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '18'
        cache: 'maven'
    - name: 'build with maven'
      run: 'mvn clean package'
    - name: 'push to google cloud'
      run: |
            docker build -t gcr.io/pacific-castle-390421/skywire:1.00 .
            docker push gcr.io/pacific-castle-390421/skywire:1.00
